"""
Notification model for storing and managing user notifications.
"""

import uuid
from datetime import datetime
from sqlalchemy import Column, String, Text, Boolean, DateTime, JSON, ForeignKey
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import relationship

from app.db.session import Base


class Notification(Base):
    """
    Notification model for delivering updates to users.

    Notifications are generated by the Coordinator Agent and delivered
    via WebSocket and stored for history.
    """
    __tablename__ = "notifications"

    id = Column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)

    # Recipient
    recipient_email = Column(String(255), nullable=False, index=True)
    recipient_id = Column(UUID(as_uuid=True), ForeignKey("persons.id"), nullable=True)

    # Notification content
    title = Column(String(500), nullable=False)
    body = Column(Text, nullable=False)
    notification_type = Column(String(50), nullable=False, index=True)  # decision, task, conflict, claim, etc.
    priority = Column(String(20), nullable=False, default="normal", index=True)  # urgent, high, normal, low

    # Related entities
    event_id = Column(UUID(as_uuid=True), ForeignKey("events.id"), nullable=True)
    decision_id = Column(UUID(as_uuid=True), ForeignKey("decisions.id"), nullable=True)
    task_id = Column(UUID(as_uuid=True), ForeignKey("tasks.id"), nullable=True)
    conflict_id = Column(UUID(as_uuid=True), ForeignKey("conflicts.id"), nullable=True)

    # Metadata
    reason = Column(String(500), nullable=True)  # Why this person is notified
    extra_data = Column(JSON, nullable=True)  # Additional context

    # Delivery tracking
    is_read = Column(Boolean, default=False, nullable=False, index=True)
    is_dismissed = Column(Boolean, default=False, nullable=False)
    delivered_at = Column(DateTime, nullable=True)  # When delivered via WebSocket
    read_at = Column(DateTime, nullable=True)

    # Timestamps
    created_at = Column(DateTime, nullable=False, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, nullable=False, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    recipient = relationship("Person", back_populates="notifications", foreign_keys=[recipient_id])
    event = relationship("Event", back_populates="notifications")
    decision = relationship("Decision", back_populates="notifications")
    task = relationship("Task", back_populates="notifications")

    def __repr__(self):
        return f"<Notification {self.id} to={self.recipient_email} type={self.notification_type}>"

    def to_dict(self):
        """Convert to dictionary for JSON serialization."""
        return {
            "id": str(self.id),
            "recipient_email": self.recipient_email,
            "title": self.title,
            "body": self.body,
            "notification_type": self.notification_type,
            "priority": self.priority,
            "reason": self.reason,
            "extra_data": self.extra_data,
            "is_read": self.is_read,
            "is_dismissed": self.is_dismissed,
            "delivered_at": self.delivered_at.isoformat() if self.delivered_at else None,
            "read_at": self.read_at.isoformat() if self.read_at else None,
            "created_at": self.created_at.isoformat(),
            "event_id": str(self.event_id) if self.event_id else None,
            "decision_id": str(self.decision_id) if self.decision_id else None,
            "task_id": str(self.task_id) if self.task_id else None,
            "conflict_id": str(self.conflict_id) if self.conflict_id else None,
        }
